contract/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/7/15'

from django.conf.urls import patterns, url
from .views import HomeContractView, AddContractView, HomeExtensionView, AddExtensionView, EditExtensionView, \
    HomeAdditionView, AddAdditionView, EditAdditionView, HomeOtherYesView, AddOtherYesView, EditOtherYesView, \
    EditContractView, DetailContractView, add_typology, add_project, add_responsive_area

urlpatterns = patterns(
    'contract.views',
    url(r'^$', HomeContractView.as_view(), name='home'),
    url(r'^detail/(?P<pk>[\d]+)/$', DetailContractView.as_view(), name='detail'),
    url(r'^add/$', AddContractView.as_view(), name='add'),
    url(r'^edit/(?P<pk>[\d]+)/$', EditContractView.as_view(), name='edit'),
    url(r'^prorrogas/$', HomeExtensionView.as_view(), name='extension_home'),
    url(r'^prorrogas/add/(?P<contract>\d+)/$', AddExtensionView.as_view(), name='extension_add_inline'),
    url(r'^prorrogas/edit/(?P<pk>\d+)/$', EditExtensionView.as_view(), name='extension_edit'),
    url(r'^adiciones/$', HomeAdditionView.as_view(), name='addition_home'),
    url(r'^adiciones/add/(?P<contract>\d+)/$', AddAdditionView.as_view(), name='addition_add_inline'),
    url(r'^adiciones/edit/(?P<pk>\d+)/$', EditAdditionView.as_view(), name='addition_edit'),
    url(r'^otrosi/$', HomeOtherYesView.as_view(), name='otheryes_home'),
    url(r'^otrosi/add/(?P<contract>\d+)/$', AddOtherYesView.as_view(), name='otheryes_add_inline'),
    url(r'^otrosi/edit/(?P<pk>\d+)/$', EditOtherYesView.as_view(), name='otheryes_edit'),
    url(r'^add/typology/$', add_typology, name='add_typology_inline'),
    url(r'^add/project/$', add_project, name='add_project_inline'),
    url(r'^add/responsive_area/$', add_responsive_area, name='add_area_inline'),
)

contratos/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'contratos.views.home', name='home'),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^contratos/', include('contract.urls', namespace='contract')),
    url(r'^contratistas/', include('contractor.urls', namespace='contractor')),
    url(r'^pagos/', include('payment.urls', namespace='payment')),

    url(r'^admin/', include(admin.site.urls)),
)

home/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '3/8/15'

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'home.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^logout/$', 'logout_view', name='logout'),
)

contract/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/7/15'
from datetime import datetime
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from contractor.models import Contractor
from home.models import TimestampUser, Typology, Project, ResponsiveArea


def contract_folder(self, name):
    return 'contracts/' + name


def extension_folder(self, name):
    return 'extensions/' + name


def otheryes_folder(self, name):
    return 'otheryes/' + name


def addition_folder(self, name):
    return 'additions/' + name


STATES_CONTRACT = (
    ('celebrado', 'Celebrado'),
    ('ejecucion', 'En ejecución'),
    ('terminado', 'Terminado'),
)


@python_2_unicode_compatible
class ContractState(models.Model):
    name_state = models.CharField(
        verbose_name='Estado de Contrato',
        max_length=100
    )

    class Meta:
        verbose_name = 'Estado de contratos'
        verbose_name_plural = 'Estados de contratos'

    def __str__(self):
        return '%s' % self.name_state


@python_2_unicode_compatible
class Contract(TimestampUser):
    contract_number = models.PositiveIntegerField(
        verbose_name='Número de contrato',
    )
    contract_year = models.PositiveIntegerField(
        default=datetime.now().year
    )
    contractor = models.ForeignKey(
        Contractor,
        verbose_name='Contratista'
    )
    typology = models.ForeignKey(
        Typology,
        verbose_name='Tipología'
    )
    contract_object = models.TextField(
        verbose_name='Objeto del contrato'
    )
    subscription_date = models.DateField(
        verbose_name='Fecha de suscripción'
    )
    init_date = models.DateField(
        verbose_name='Fecha de inicio'
    )
    end_date = models.DateField(
        verbose_name='Fecha de terminación'
    )
    project = models.ForeignKey(
        Project,
        verbose_name='Proyecto'
    )
    responsive_area = models.ForeignKey(
        ResponsiveArea,
        verbose_name='Área responsable'
    )
    total_amount = models.PositiveIntegerField(
        verbose_name='Valor total'
    )
    advance_amount = models.PositiveIntegerField(
        verbose_name='Valor anticipo'
    )
    policy_number = models.CharField(
        verbose_name='Número de póliza',
        max_length=50
    )
    scan = models.FileField(
        verbose_name='Archivo digital',
        upload_to=contract_folder,
        blank=True,
        null=True
    )
    archive = models.CharField(
        verbose_name='Ubicación física',
        max_length=10,
        blank=True
    )
    state = models.CharField(
        verbose_name='Estado del contrato',
        default='celebrado',
        choices=STATES_CONTRACT,
        max_length=50
    )

    class Meta:
        verbose_name = 'Contrato',
        verbose_name_plural = 'Contratos'

    def __str__(self):
        return '%d - %d' % (self.contract_number, self.contract_year)

    def get_term(self):
        return (self.end_date - self.init_date).days

    def get_contract_number(self):
        return '%d - %d' % (self.contract_number, self.contract_year)


@python_2_unicode_compatible
class Extension(TimestampUser):
    contract = models.ForeignKey(
        Contract,
        verbose_name='Contrato'
    )
    end_date = models.DateField(
        verbose_name='Fecha de terminación'
    )
    scan = models.FileField(
        verbose_name='Archivo digital',
        blank=True,
        null=True,
        upload_to=extension_folder
    )

    class Meta:
        verbose_name = 'Prórroga',
        verbose_name_plural = 'Prórrogas'

    def __str__(self):
        return 'Prorroga contrato No. %d-%d' % (self.contract.contract_number, self.contract.contract_year)


@python_2_unicode_compatible
class Addition(TimestampUser):
    contract = models.ForeignKey(
        Contract,
        verbose_name='Contrato'
    )
    value = models.PositiveIntegerField(
        verbose_name='Valor adición'
    )
    scan = models.FileField(
        verbose_name='Archivo digital',
        blank=True,
        null=True,
        upload_to=addition_folder
    )

    class Meta:
        verbose_name = 'Adición'
        verbose_name_plural = 'Adiciones'

    def __str__(self):
        return 'Adición contrato No %d-%d' % (self.contract.contract_number, self.contract.contract_year)


@python_2_unicode_compatible
class OtherYes(TimestampUser):
    contract = models.ForeignKey(
        Contract,
        verbose_name='Contrato'
    )
    description = models.TextField(
        verbose_name='Descripción',
        max_length=500
    )
    scan = models.FileField(
        verbose_name='Archivo digital',
        blank=True,
        null=True,
        upload_to=otheryes_folder
    )

    class Meta:
        verbose_name = 'Otro Sí'
        verbose_name_plural = 'Otro Sí'

    def __str__(self):
        return 'Otro Sí contrato No %d-%d' % (self.contract.contract_number, self.contract.contract_year)

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/7/15'
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class TimestampUser(models.Model):
    """
    Abstract class with timestamps and user fields
    """
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        User
    )

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Project(models.Model):
    name_resource = models.CharField(
        verbose_name='Proyecto',
        max_length=100
    )

    class Meta:
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'
        ordering = ['name_resource']

    def __str__(self):
        return '%s' % self.name_resource


@python_2_unicode_compatible
class ResponsiveArea(models.Model):
    name_area = models.CharField(
        verbose_name='Área responsable',
        max_length=100
    )
    responsive = models.CharField(
        verbose_name='Persona responsable',
        max_length=150
    )
    email = models.EmailField(
        verbose_name='Correo electrónico',
    )

    class Meta:
        verbose_name = 'Área responsable'
        verbose_name_plural = 'Áreas responsables'
        ordering = ['name_area']

    def __str__(self):
        return '%s' % self.name_area


@python_2_unicode_compatible
class Typology(models.Model):
    name_typology = models.CharField(
        verbose_name='Tipología',
        max_length=100
    )

    class Meta:
        verbose_name = 'Tipología',
        verbose_name_plural = 'Tipologías'
        ordering = ['name_typology']

    def __str__(self):
        return '%s' % self.name_typology

contract/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

__author__ = 'gollum23'
__date__ = '3/7/15'

from django import forms
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, CreateView, UpdateView, DetailView, FormView
from django.utils.html import escape

from .models import Contract, Extension, Addition, OtherYes
from .forms import ContractForm, ExtensionForm, AdditionForm, OtherYesForm, FilterForm
from home.mixins import LoginRequiredMixin
from home.forms import TypologyForm, ProjectForm, ResponsiveAreaForm


# Views contracts
class HomeContractView(LoginRequiredMixin, FormView, ListView):
    model = Contract
    template_name = 'contract/index.html'
    form_class = FilterForm
    state = ''
    area = ''
    project = ''
    typology = ''
    year = ''
    amount = 0
    data = {}

    def get_queryset(self):
        self.data = {
            'state': self.state,
            'area': self.area,
            'project': self.project,
            'typology': self.typology,
            'year': self.year,
            'amount': self.amount
        }
        queryset = self.model.objects.all().order_by('-contract_year', '-contract_number')
        if self.request.GET.get('state') is not None and self.request.GET.get('state') != '':
            state = self.request.GET.get('state')
            self.data['state'] = state
            queryset = queryset.filter(state=state)
        if self.request.GET.get('area') is not None and self.request.GET.get('area') != '':
            area = int(self.request.GET.get('area'))
            self.data['area'] = area
            queryset = queryset.filter(responsive_area=area)
        if self.request.GET.get('project') is not None and self.request.GET.get('project') != '':
            project = int(self.request.GET.get('project'))
            self.data['project'] = project
            queryset = queryset.filter(project=project)
        if self.request.GET.get('typology') is not None and self.request.GET.get('typology') != '':
            typology = int(self.request.GET.get('typology'))
            self.data['typology'] = typology
            queryset = queryset.filter(typology=typology)
        if self.request.GET.get('year') is not None and self.request.GET.get('year') != '':
            year = int(self.request.GET.get('year'))
            self.data['year'] = year
            queryset = queryset.filter(contract_year=year)
        if self.request.GET.get('amount') is not None and self.request.GET.get('amount') != '':
            amount = int(self.request.GET.get('amount'))
            self.data['amount'] = amount
            if amount == 1:
                queryset = queryset.filter(total_amount__lte=10000000)
            elif amount == 2:
                queryset = queryset.filter(total_amount__gt=10000000, total_amount__lte=50000000)
            elif amount == 3:
                queryset = queryset.filter(total_amount__gt=50000000)
            else:
                queryset = queryset
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HomeContractView, self).get_context_data(**kwargs)
        context['form'] = self.form_class(initial=self.data)
        return context


class DetailContractView(LoginRequiredMixin, DetailView):
    model = Contract
    template_name = 'contract/detail.html'


class AddContractView(LoginRequiredMixin, CreateView):
    form_class = ContractForm
    template_name = 'contract/add_edit.html'
    success_url = reverse_lazy('contract:home')


class EditContractView(LoginRequiredMixin, UpdateView):
    model = Contract
    form_class = ContractForm
    template_name = 'contract/add_edit.html'
    success_url = reverse_lazy('contract:home')


# Views Extensions
class HomeExtensionView(LoginRequiredMixin, ListView):
    model = Extension
    template_name = 'extension/index.html'

    def get_queryset(self):
        queryset = self.model.objects.all().order_by('-created_at')
        return queryset


class AddExtensionView(LoginRequiredMixin, CreateView):
    form_class = ExtensionForm
    template_name = 'extension/add_edit.html'
    success_url = reverse_lazy('contract:home')

    def get_context_data(self, **kwargs):
        context = super(AddExtensionView, self).get_context_data(**kwargs)
        context['contrato'] = Contract.objects.get(pk=self.kwargs['contract'])
        return context


class EditExtensionView(LoginRequiredMixin, UpdateView):
    model = Extension
    form_class = ExtensionForm
    template_name = 'extension/add_edit.html'
    success_url = reverse_lazy('contract:extension_home')


# Views Additions
class HomeAdditionView(LoginRequiredMixin, ListView):
    model = Addition
    template_name = 'addition/index.html'

    def get_queryset(self):
        queryset = self.model.objects.all().order_by('-created_at')
        return queryset


class AddAdditionView(LoginRequiredMixin, CreateView):
    form_class = AdditionForm
    template_name = 'addition/add_edit.html'
    success_url = reverse_lazy('contract:home')

    def get_context_data(self, **kwargs):
        context = super(AddAdditionView, self).get_context_data(**kwargs)
        context['contrato'] = Contract.objects.get(pk=self.kwargs['contract'])
        return context


class EditAdditionView(LoginRequiredMixin, UpdateView):
    model = Addition
    form_class = AdditionForm
    template_name = 'addition/add_edit.html'
    success_url = reverse_lazy('contract:addition_home')


# Views Otheryes
class HomeOtherYesView(LoginRequiredMixin, ListView):
    model = OtherYes
    template_name = 'otheryes/index.html'

    def get_queryset(self):
        queryset = self.model.objects.all().order_by('-created_at')
        return queryset


class AddOtherYesView(LoginRequiredMixin, CreateView):
    form_class = OtherYesForm
    template_name = 'otheryes/add_edit.html'
    success_url = reverse_lazy('contract:home')

    def get_context_data(self, **kwargs):
        context = super(AddOtherYesView, self).get_context_data(**kwargs)
        context['contrato'] = Contract.objects.get(pk=self.kwargs['contract'])
        return context


class EditOtherYesView(LoginRequiredMixin, UpdateView):
    model = OtherYes
    form_class = OtherYesForm
    template_name = 'otheryes/add_edit.html'
    success_url = reverse_lazy('contract:otheryes_home')


# Inlines
def handle_pop_up_add(request, add_form, field):
    form = add_form(request.POST or None)
    if form.is_valid():
        try:
            new_object = form.save()
        except forms.ValidationError:
            new_object = None
        if new_object:
            return HttpResponse(
                '<script type="text/javascript">opener.dismissAddAnotherPopup(window, "%s", "%s");</script>' %
                (escape(new_object._get_pk_val()), escape(new_object)))
    ctx = {
        'form': form,
        'field': field
    }
    # if field == 'contractor':
    #     template = 'popaddcontrator.html'
    template = 'popaddtypology.html'
    if field == 'typology':
        template = 'popaddtypology.html'
    if field == 'project':
        template = 'popaddproject.html'
    if field == 'responsive_area':
        template = 'popaddarea.html'
    return render(request, template, ctx)


@login_required(login_url='/')
def add_typology(request):
    return handle_pop_up_add(request, TypologyForm, 'typology')


@login_required(login_url='/')
def add_project(request):
    return handle_pop_up_add(request, ProjectForm, 'project')


@login_required(login_url='/')
def add_responsive_area(request):
    return handle_pop_up_add(request, ResponsiveAreaForm, 'responsive_area')

contract/templates/contract/detail.html
{% extends 'base__loged.html' %}
{% load humanize %}
{% block main--loged %}
    <div class="header__modules">
        <h2 class="header__modules__title">Contrato {{ object.get_contract_number }}</h2>
        <div class="header__modules__actions">
            <a href="javascript:history.back()" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Listado de contratos</a>
        </div>
    </div>
    <section class="detail">
        <div class="column column--left">
            <div class="detail__item">
                <span>Contratista:</span><p><a href="{% url 'contractor:detail' object.contractor.id %}">{{ object.contractor.name }}</a></p>
            </div>
            <div class="detail__item">
                <span>Fecha suscripción:</span>
                <p>{{ object.subscription_date }}</p>
            </div>
        </div>
        <div class="column column-center">
            <div class="detail__item">
                <span>Estado:</span>
                <p>{{ object.get_state_display }}</p>
            </div>
            <div class="detail__item">
                <span>Fecha de inicio:</span>
                <p>{{ object.init_date }}</p>
            </div>
        </div>
        <div class="column column-right">
            <div class="detail__item">
                <span>Tipo:</span>
                <p>{{ object.typology.name_typology }}</p>
            </div>
            <div class="detail__item">
                <span>Fecha de terminación:</span>
                <p>{{ object.end_date }}</p>
            </div>
        </div>
        <div class="column column--fullwidth">
            <div class="detail__item">
                <span>Objeto:</span>
                <p>{{ object.contract_object }}</p>
            </div>
        </div>
        <div class="column column--left">
            <div class="detail__item">
                <span>Proyecto:</span><p>{{ object.project.name_resource }}</p>
            </div>
            <div class="detail__item">
                <span>Monto total:</span>
                <p>$ {{ object.total_amount|intcomma }}</p>
            </div>
            <div class="detail__item">
                <span>Ubicación física:</span>
                <p>{% if object.archive %}{{ object.archive }}{% else %}No se ha ingresado la ubicación{% endif %}</p>
            </div>
        </div>
        <div class="column column-center">
            <div class="detail__item">
                <span>Área responsable:</span>
                <p>{{ object.responsive_area.name_area }}</p>
            </div>
            <div class="detail__item">
                <span>Monto avance:</span>
                <p>$ {{ object.advance_amount|intcomma }}</p>
            </div>
        </div>
        <div class="column column-right">
            <div class="detail__item">
                <span>Documento digital:</span>
                <p>{% if object.scan %}<a href="{{ MEDIA_URL }}{{ object.scan }}" target="_blank">Contrato</a>{% else %}No se ha subido el contrato{% endif %}</p>
            </div>
            <div class="detail__item">
                <span>No de Póliza:</span>
                <p>{{ object.policy_number }}</p>
            </div>
        </div>
        <h3>Prórrogas</h3>
        {% for p in object.extension_set.all %}
            <div class="column column--halfwidth">
                <div class="detail__item">
                    <span>Fecha de terminación:</span>
                    <p>{{ p.end_date }} </p>
                </div>
            </div>
            <div class="column column--halfwidth">
                <div class="detail__item">
                    <span>Documento:</span>
                    <p>{% if p.scan %}<a href="{{ MEDIA_URL }}{{ p.scan }}" target="_blank">Prorroga</a>{% else %}No se ha subido la prorroga{% endif %}</p>
                </div>
            </div>
        {% empty %}
            <h4>Este contrato no tiene prorrogas</h4>
        {% endfor %}
        <h3>Adiciones</h3>
        {% for p in object.addition_set.all %}
            <div class="column column--halfwidth">
                <div class="detail__item">
                    <span>Valor adición:</span>
                    <p>{{ p.value }} </p>
                </div>
            </div>
            <div class="column column--halfwidth">
                <div class="detail__item">
                    <span>Documento:</span>
                    <p>{% if p.scan %}<a href="{{ MEDIA_URL }}{{ p.scan }}" target="_blank">Adición</a>{% else %}No se ha subido la adición{% endif %}</p>
                </div>
            </div>
        {% empty %}
            <h4>Este contrato no tiene adiciones</h4>
        {% endfor %}
        <h3>Otrosi</h3>
        {% for p in object.otheryes_set.all %}
            <div class="column column--halfwidth">
                <div class="detail__item">
                    <span>Descripción:</span>
                    <p>{{ p.description }} </p>
                </div>
            </div>
            <div class="column column--halfwidth">
                <div class="detail__item">
                    <span>Documento:</span>
                    <p>{% if p.scan %}<a href="{{ MEDIA_URL }}{{ p.scan }}" target="_blank">Otrosi</a>{% else %}No se ha subido el otro sí{% endif %}</p>
                </div>
            </div>
        {% empty %}
            <h4>Este contrato no tiene otrosí</h4>
        {% endfor %}
    </section>
{% endblock %}

contract/templates/contract/index.html
{% extends 'base__loged.html' %}
{% load static from staticfiles %}
{% load humanize %}
{% block main--loged %}
    <div class="header__modules">
        <h2 class="header__modules__title">Contratos</h2>
        <div class="header__modules__actions">
            {% if user.is_staff %}
            <a href="{% url 'contract:add' %}" class="btn btn--default"><i class="fa fa-plus-circle"></i> Agregar Contratos</a>
            {% endif %}
        </div>
    </div>
    <div class="filter__modules">
        <form action="." method="get" class="form__filter">
            {% for f in form %}
                <div class="filter__item">
                    {{ f.label_tag }}{{ f }}
                </div>
            {% endfor %}
            <div class="filter__actions">
                <button type="reset" id="reset_filter_form" class="btn btn--warning"><i class="fa fa-close"></i> Resetear</button>
                <button type="submit" class="btn btn--success"><i class="fa fa-filter"></i> Filtrar</button>
            </div>
        </form>
    </div>
    <section class="list__items__module">
        <table>
            <thead>
                <tr>
                    <th>No</th>
                    <th>Contratista</th>
                    <th>Tipo</th>
                    <th>Inicio</th>
                    <th>Fin</th>
                    <th>Monto</th>
                    <th>Estado</th>
                    <th></th>
                    {% if user.is_staff %}
                        <th></th>
                        <th></th>
                        <th></th>
                        <th></th>
                    {% endif %}
                </tr>
            </thead>
            <tbody>
                {% for c in object_list %}
                    <tr>
                        <td>{{ c.contract_number }}-{{ c.contract_year }}</td>
                        <td>{{ c.contractor.name }}</td>
                        <td>{{ c.typology.name_typology }}</td>
                        <td>{{ c.init_date|date:'d/m/Y' }}</td>
                        <td>{{ c.end_date|date:'d/m/Y' }}</td>
                        <td>$ {{ c.total_amount|intcomma }}</td>
                        <td>{{ c.get_state_display }}</td>
                        <td><a class="btn btn--default" href="{% url 'contract:detail' c.id %}" title="Detalle"><i class="fa fa-eye"></i></a></td>
                        {% if user.is_staff %}
                            <td><a class="btn btn--default" href="{% url 'contract:edit' c.id %}" title="Editar"><i class="fa fa-edit"></i></a></td>
                            <td><a class="btn btn--warning" href="{% url 'contract:extension_add_inline' c.id %}" title="Prorroga"><i class="fa fa-calendar"></i></a></td>
                            <td><a class="btn btn--warning" href="{% url 'contract:addition_add_inline' c.id %}" title="Adición"><i class="fa fa-dollar"></i></a></td>
                            <td><a class="btn btn--warning" href="{% url 'contract:otheryes_add_inline' c.id %}" title="Otro Si"><i class="fa fa-file-text-o"></i></a></td>
                        {% endif %}
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </section>
{% endblock %}
{% block JS %}
    {{ block.super }}
    <script src="{% static 'js/contract_app_index.js' %}"></script>
{% endblock %}