contractor/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '3/8/15'

from django.conf.urls import patterns, url

from .views import AddContractorView, HomeContractorView, EditContractorView, DetailContractorView

urlpatterns = patterns(
    'contractor.views',
    url(r'^$', HomeContractorView.as_view(), name='home'),
    url(r'^add/$', AddContractorView.as_view(), name='add'),
    url(r'^edit/(?P<pk>\d+)/$', EditContractorView.as_view(), name='edit'),
    url(r'^detail/(?P<pk>\d+)/$', DetailContractorView.as_view(), name='detail')
)

contratos/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'contratos.views.home', name='home'),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^contratos/', include('contract.urls', namespace='contract')),
    url(r'^contratistas/', include('contractor.urls', namespace='contractor')),
    url(r'^pagos/', include('payment.urls', namespace='payment')),

    url(r'^admin/', include(admin.site.urls)),
)

home/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '3/8/15'

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'home.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^logout/$', 'logout_view', name='logout'),
)

contractor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/7/15'

from django.core.validators import MinValueValidator, MaxValueValidator
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from home.models import TimestampUser


@python_2_unicode_compatible
class IdentificationType(models.Model):
    name_idtype = models.CharField(
        verbose_name='Tipo de identificación',
        max_length=20
    )

    class Meta:
        verbose_name = 'Tipo de identificación'
        verbose_name_plural = 'Tipos de identificación'

    def __str__(self):
        return '%s' % self.name_idtype


@python_2_unicode_compatible
class Contractor(TimestampUser):
    identification_type = models.ForeignKey(
        IdentificationType,
        verbose_name='Tipo de identificación'
    )
    identification = models.PositiveIntegerField(
        verbose_name='Identificación'
    )
    dv = models.PositiveSmallIntegerField(
        validators=[
            MinValueValidator(0),
            MaxValueValidator(9)
        ],
        blank=True,
        null=True
    )
    name = models.CharField(
        verbose_name='Nombre',
        max_length=150
    )
    address = models.CharField(
        verbose_name='Dirección',
        max_length=255
    )
    phone = models.PositiveIntegerField(
        verbose_name='Teléfono'
    )
    cellphone = models.BigIntegerField(
        verbose_name='Celular',
        blank=True
    )
    agent = models.CharField(
        verbose_name='Representante Legal',
        max_length=150,
        blank=True
    )

    class Meta:
        verbose_name = 'Contratista'
        verbose_name_plural = 'Contratistas'

    def __str__(self):
        return '%s' % self.name

home/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/7/15'
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible


class TimestampUser(models.Model):
    """
    Abstract class with timestamps and user fields
    """
    created_at = models.DateTimeField(
        auto_now_add=True
    )
    updated_at = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        User
    )

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Project(models.Model):
    name_resource = models.CharField(
        verbose_name='Proyecto',
        max_length=100
    )

    class Meta:
        verbose_name = 'Proyecto'
        verbose_name_plural = 'Proyectos'
        ordering = ['name_resource']

    def __str__(self):
        return '%s' % self.name_resource


@python_2_unicode_compatible
class ResponsiveArea(models.Model):
    name_area = models.CharField(
        verbose_name='Área responsable',
        max_length=100
    )
    responsive = models.CharField(
        verbose_name='Persona responsable',
        max_length=150
    )
    email = models.EmailField(
        verbose_name='Correo electrónico',
    )

    class Meta:
        verbose_name = 'Área responsable'
        verbose_name_plural = 'Áreas responsables'
        ordering = ['name_area']

    def __str__(self):
        return '%s' % self.name_area


@python_2_unicode_compatible
class Typology(models.Model):
    name_typology = models.CharField(
        verbose_name='Tipología',
        max_length=100
    )

    class Meta:
        verbose_name = 'Tipología',
        verbose_name_plural = 'Tipologías'
        ordering = ['name_typology']

    def __str__(self):
        return '%s' % self.name_typology

contractor/forms.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/11/15'

from django import forms

from .models import Contractor


class ContractorForm(forms.ModelForm):
    identification = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'class': 'input--auto-width',
                'placeholder': 'Número'
            }
        )
    )
    dv = forms.IntegerField(
        widget=forms.TextInput(
            attrs={'class': 'input--d2'}
        ),
        required=False
    )
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Nombre', 'class': 'full-width'}
        )
    )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Dirección', 'class': 'full-width'}
        )
    )
    phone = forms.IntegerField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono', 'class': 'full-width'}
        )
    )
    cellphone = forms.IntegerField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Celular', 'class': 'full-width'}
        ),
        required=False
    )
    agent = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Representate legal', 'class': 'full-width'}
        ),
        required=False
    )

    class Meta:
        model = Contractor
        fields = '__all__'


class FilterContractForm(forms.Form):
    name = forms.CharField(
        label='Nombre',
        max_length=255
    )
    identification = forms.IntegerField(
        widget=forms.TextInput(),
        label='Identificación'
    )

contractor/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
__author__ = 'gollum23'
__date__ = '3/7/15'

from django.core.urlresolvers import reverse_lazy
from django.views.generic import ListView, DetailView, FormView
from django.views.generic.edit import CreateView, UpdateView

from .forms import ContractorForm, FilterContractForm
from .models import Contractor
from home.mixins import LoginRequiredMixin


class HomeContractorView(LoginRequiredMixin, FormView, ListView):
    model = Contractor
    template_name = 'contractor__index.html'
    form_class = FilterContractForm
    data = {}

    def get_queryset(self):
        self.data = {
            'name': '',
            'identification': ''
        }
        queryset = self.model.objects.all().order_by('name')
        if self.request.GET.get('name') is not None and self.request.GET.get('name') != '':
            by_name = self.request.GET.get('name')
            self.data['name'] = by_name
            queryset = queryset.filter(name__icontains=by_name)
        if self.request.GET.get('identification') is not None and self.request.GET.get('identification') != '':
            by_id = self.request.GET.get('identification')
            self.data['identification'] = by_id
            queryset = queryset.filter(identification__icontains=by_id)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(HomeContractorView, self).get_context_data(**kwargs)
        context['form'] = self.form_class(initial=self.data)
        return context


class AddContractorView(LoginRequiredMixin, CreateView):
    form_class = ContractorForm
    template_name = 'contractor__add.html'
    success_url = reverse_lazy('contractor:home')


class EditContractorView(LoginRequiredMixin, UpdateView):
    model = Contractor
    form_class = ContractorForm
    template_name = 'contractor__edit.html'
    success_url = reverse_lazy('contractor:home')


class DetailContractorView(LoginRequiredMixin, DetailView):
    model = Contractor
    template_name = 'contractor__detail.html'

contractor/templates/contractor__add.html
{% extends 'base__loged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="header__modules">
        <h2 class="header__modules__title">Agregar contratista</h2>
        <div class="header__modules__actions">
            <a href="{% url 'contractor:home' %}" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <section class="form__modules">
        <form action="." method="post" id="formContractor">
            {% csrf_token %}
            <input id="id_user" name="user" type="hidden" value="{{ user.id }}"/>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.identification_type.label_tag }}</div>
                <div class="half-width">{{ form.identification.label_tag }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.identification_type }}</div>
                <div class="half-width">{{ form.identification }} - {{ form.dv }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.identification_type.errors }}</div>
                <div class="half-width">{{ form.identification.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.name }}</div>
                <div class="half-width">{{ form.address }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.name.errors }}</div>
                <div class="half-width">{{ form.address.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="quarter-width">{{ form.phone }}</div>
                <div class="quarter-width">{{ form.cellphone }}</div>
                <div class="half-width">{{ form.agent }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="quarter-width">{{ form.phone.errors }}</div>
                <div class="quarter-width">{{ form.cellphone.errors }}</div>
                <div class="half-width">{{ form.agent.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-right">
                <button class="btn btn--default" type="submit"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
{% endblock %}
{% block JS %}
    {{ block.super }}
    <script src="{% static 'js/contractor_app.js' %}"></script>
{% endblock %}

contractor/templates/contractor__detail.html
{% extends 'base__loged.html' %}
{% load humanize %}
{% block main--loged %}
    <div class="header__modules">
        <h2 class="header__modules__title">{{ object.name }}</h2>
        <div class="header__modules__actions">
            <a href="javascript:history.back()" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Listado de contratos</a>
        </div>
    </div>
    <section class="detail">
        <div class="column column--left">
            <div class="detail__item">
                <span>Identificación:</span><p>{{ object.identification_type.name_idtype }}: {{ object.identification }}{% if object.dv %}-{{ object.dv }}{% endif %}</p>
            </div>
            <div class="detail__item">
                <span>Dirección:</span>
                <p>{{ object.address }}</p>
            </div>
        </div>
        <div class="column column-center">
            <div class="detail__item">
                <span>Nombre completo:</span>
                <p>{{ object.name }}</p>
            </div>
            <div class="detail__item">
                <span>Teléfono:</span>
                <p>{{ object.phone }}</p>
            </div>
        </div>
        <div class="column column-right">
            <div class="detail__item">
                <span>Representante legal:</span>
                <p>{% if object.agent %}{{ object.agent }}{% endif %}</p>
            </div>
            <div class="detail__item">
                <span>Celular:</span>
                <p>{{ object.cellphone }}</p>
            </div>
        </div>
        <h3>Contratos</h3>
        {% for c in object.contract_set.all %}
            <div class="column column-left">
                <div class="detail__item">
                    <span>Contrato No:</span>
                    <p><a href="{% url 'contract:detail' c.id %}">{{ c.get_contract_number }}</a></p>
                </div>
            </div>
            <div class="column column-center">
                <div class="detail__item">
                    <span>Fecha de suscripción:</span>
                    <p>{{ c.subscription_date }}</p>
                </div>
            </div>
            <div class="column column-right">
                <div class="detail__item">
                    <span>Monto:</span>
                    <p>$ {{ c.total_amount|intcomma }}</p>
                </div>
            </div>
        {% empty %}
            <h4>Este contratista no tiene contratos</h4>
        {% endfor %}
    </section>
{% endblock %}

contractor/templates/contractor__edit.html
{% extends 'base__loged.html' %}
{% block main--loged %}
    <div class="header__modules">
        <h2 class="header__modules__title">Agregar contratista</h2>
        <div class="header__modules__actions">
            <a href="{% url 'contractor:home' %}" class="btn btn--default"><i class="fa fa-arrow-circle-left"></i> Volver al listado</a>
        </div>
    </div>
    <section class="form__modules">
        <form action="." method="post">
            {% csrf_token %}
            <input id="id_user" name="user" type="hidden" value="{{ user.id }}"/>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.identification_type.label_tag }}</div>
                <div class="half-width">{{ form.identification.label_tag }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.identification_type }}</div>
                <div class="half-width">{{ form.identification }} - {{ form.dv }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.identification_type.errors }}</div>
                <div class="half-width">{{ form.identification.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.name }}</div>
                <div class="half-width">{{ form.address }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="half-width">{{ form.name.errors }}</div>
                <div class="half-width">{{ form.address.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="quarter-width">{{ form.phone }}</div>
                <div class="quarter-width">{{ form.cellphone }}</div>
                <div class="half-width">{{ form.agent }}</div>
            </div>
            <div class="form-modules--row form-modules--row-justify">
                <div class="quarter-width">{{ form.phone.errors }}</div>
                <div class="quarter-width">{{ form.cellphone.errors }}</div>
                <div class="half-width">{{ form.agent.errors }}</div>
            </div>
            <div class="form-modules--row form-modules--row-right">
                <button class="btn btn--default" type="submit"><i class="fa fa-save"></i> Guardar</button>
            </div>
        </form>
    </section>
{% endblock %}
{% block JS %}

{% endblock %}

contractor/templates/contractor__index.html
{% extends 'base__loged.html' %}
{% load static from staticfiles %}
{% block main--loged %}
    <div class="header__modules">
        <h2 class="header__modules__title">Contratistas</h2>
        <div class="header__modules__actions">
            {% if user.is_staff %}
                <a href="{% url 'contractor:add' %}" class="btn btn--default"><i class="fa fa-plus-circle"></i> Agregar Contratista</a>
            {% endif %}
        </div>
    </div>
    <div class="filter__modules">
        <form action="." method="get" class="form__filter">
            {% for f in form %}
                <div class="filter__item filter__item--half">
                    {{ f.label_tag }}{{ f }}
                </div>
            {% endfor %}
            <div class="filter__actions">
                <button type="reset" id="reset_filter_form" class="btn btn--warning"><i class="fa fa-close"></i> Resetear</button>
                <button type="submit" class="btn btn--success"><i class="fa fa-filter"></i> Filtrar</button>
            </div>
        </form>
    </div>
    <section class="list__items__module">
        <table>
            <tr>
                <th>Nombre</th>
                <th>Identificación</th>
                <th>Teléfono</th>
                <th>Celular</th>
                <th></th>
                {% if user.is_staff %}
                    <th></th>
                {% endif %}
            </tr>
            {% for c in object_list %}
                <tr>
                    <td>{{ c.name }}</td>
                    <td>{{ c.identification }}{% if c.dv %}-{{ c.dv }}{% endif %}</td>
                    <td>{{ c.phone }}</td>
                    <td>{{ c.cellphone }}</td>
                    <td><a class="btn btn--default" href="{% url 'contractor:detail' c.id %}"><i class="fa fa-file-text-o"></i></a></td>
                    {% if user.is_staff %}
                        <td><a class="btn btn--default" href="{% url 'contractor:edit' c.id %}"><i class="fa fa-edit"></i></a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
    </section>
{% endblock %}
{% block JS %}
    {{ block.super }}
    <script src="{% static 'js/contractor_app_index.js' %}"></script>
{% endblock %}