contratos/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns(
    '',
    # Examples:
    # url(r'^$', 'contratos.views.home', name='home'),
    url(r'^', include('home.urls', namespace='home')),
    url(r'^contratos/', include('contract.urls', namespace='contract')),
    url(r'^contratistas/', include('contractor.urls', namespace='contractor')),
    url(r'^pagos/', include('payment.urls', namespace='payment')),

    url(r'^admin/', include(admin.site.urls)),
)

home/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '3/8/15'

from django.conf.urls import patterns, url

urlpatterns = patterns(
    'home.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^logout/$', 'logout_view', name='logout'),
)

templates/base.html
{% load static from staticfiles %}
<!doctype html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <title>Seguimiento de contratos</title>
    <link rel="stylesheet" href="{% static 'css/normalize.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/styles.css' %}"/>
    {% block extraCSS %}{% endblock %}
</head>
<body>
    {% block header %}{% endblock %}

    {% block main %}{% endblock %}

    {% block footer %}{% endblock %}
    {% block JS %}{% endblock %}
</body>
</html>

templates/base__loged.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block header %}
    <header>{% block header--loged %}
        <h2 class="brand">Fundación Escuela Taller Bogota</h2>
        <div class="user">
            {{ user.get_full_name }}
        </div>
        <div class="user__menu is_hidden">
            <ul>
                <li><a href="{% url 'home:logout' %}">Cerrar sesión</a></li>
            </ul>
        </div>
    {% endblock %}</header>
{% endblock %}
{% block main %}
    <div class="wrapper">
        <section class="sidebar">
            <ul class="nav">
                {% for i in menu %}
                    <li><a href="{{ i.url }}" {% if i.active %}class="active" {% endif %}><i class="fa fa-{{ i.icon }}"></i>{{ i.name }}</a></li>
                {% endfor %}
            </ul>
        </section>
        <section class="main--login">
            {% block main--loged %}{% endblock %}
        </section>
    </div>
{% endblock %}
{% block footer %}
{#    <footer>{% block footer--loged %}{% endblock %}</footer>#}
{% endblock %}
{% block JS %}
    <script src="{% static 'js/vendor/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
{% endblock %}